// Code generated by protoc-gen-go. DO NOT EDIT.
// source: containerd.proto
// protoc:3.13.0
// protoc-gen-go 1.3.5

package v1

import (
	"context"
	"fmt"
	"github.com/golang/protobuf/proto"
	"github.com/golang/protobuf/ptypes/any"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf
var _ = proto.Marshal

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Container struct {
	// ID the container id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Labels the container labels
	Labels map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Image the container image
	Image string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	// Spec  runtime specific.
	Spec                 *any.Any `protobuf:"bytes,5,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

// Reset reset the object
func (m *Container) Reset() { *m = Container{} }

// String
func (m *Container) String() string { return proto.CompactTextString(m) }

// ProtoMessage
func (*Container) ProtoMessage() {}

// Descriptor
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_29bcc067d8d1b7d0, []int{0}
}

// XXX_Unmarshal
func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}

// XXX_Marshal
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}

// XXX_Merge
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}

// XXX_Size
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}

// XXX_DiscardUnknown
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

// GetId
func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// GetLabels
func (m *Container) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

// GetImage
func (m *Container) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

// GetSpec
func (m *Container) GetSpec() *any.Any {
	if m != nil {
		return m.Spec
	}
	return nil
}

type GetContainerRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContainerRequest) Reset()         { *m = GetContainerRequest{} }
func (m *GetContainerRequest) String() string { return proto.CompactTextString(m) }
func (*GetContainerRequest) ProtoMessage()    {}
func (*GetContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_29bcc067d8d1b7d0, []int{1}
}

func (m *GetContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContainerRequest.Unmarshal(m, b)
}
func (m *GetContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContainerRequest.Marshal(b, m, deterministic)
}
func (m *GetContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContainerRequest.Merge(m, src)
}
func (m *GetContainerRequest) XXX_Size() int {
	return xxx_messageInfo_GetContainerRequest.Size(m)
}
func (m *GetContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContainerRequest proto.InternalMessageInfo

func (m *GetContainerRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetContainerResponse struct {
	Container            *Container `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetContainerResponse) Reset()         { *m = GetContainerResponse{} }
func (m *GetContainerResponse) String() string { return proto.CompactTextString(m) }
func (*GetContainerResponse) ProtoMessage()    {}
func (*GetContainerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_29bcc067d8d1b7d0, []int{2}
}

func (m *GetContainerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContainerResponse.Unmarshal(m, b)
}
func (m *GetContainerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContainerResponse.Marshal(b, m, deterministic)
}
func (m *GetContainerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContainerResponse.Merge(m, src)
}
func (m *GetContainerResponse) XXX_Size() int {
	return xxx_messageInfo_GetContainerResponse.Size(m)
}
func (m *GetContainerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContainerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetContainerResponse proto.InternalMessageInfo

func (m *GetContainerResponse) GetContainer() *Container {
	if m != nil {
		return m.Container
	}
	return nil
}

func init() {
	proto.RegisterType((*Container)(nil), "containerd.services.containers.v1.Container")
	proto.RegisterMapType((map[string]string)(nil), "containerd.services.containers.v1.Container.LabelsEntry")
	proto.RegisterType((*GetContainerRequest)(nil), "containerd.services.containers.v1.GetContainerRequest")
	proto.RegisterType((*GetContainerResponse)(nil), "containerd.services.containers.v1.GetContainerResponse")
}

func init() {
	proto.RegisterFile("containerd.proto", fileDescriptor_29bcc067d8d1b7d0)
}

var fileDescriptor_29bcc067d8d1b7d0 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x4f, 0x4b, 0xc3, 0x30,
	0x14, 0xa7, 0xad, 0x1b, 0xec, 0x15, 0x64, 0xc4, 0x1d, 0xea, 0x4e, 0x73, 0x20, 0xf4, 0xa0, 0xa9,
	0xab, 0xa0, 0x53, 0x4f, 0x2a, 0x32, 0x10, 0x0f, 0xd2, 0xa3, 0xb7, 0xb6, 0x7b, 0xce, 0x62, 0x96,
	0xd4, 0x24, 0xad, 0xf6, 0xee, 0x87, 0xf5, 0x63, 0xc8, 0xd2, 0xad, 0x4e, 0x11, 0x74, 0xb7, 0xf7,
	0x5e, 0x7f, 0x7f, 0x1b, 0xe8, 0xa6, 0x82, 0xeb, 0x38, 0xe3, 0x28, 0xa7, 0x34, 0x97, 0x42, 0x0b,
	0xb2, 0xb7, 0x76, 0x51, 0x28, 0xcb, 0x2c, 0x45, 0x45, 0x9b, 0x9b, 0xa2, 0xe5, 0xa8, 0xbf, 0x3b,
	0x13, 0x62, 0xc6, 0x30, 0x30, 0x84, 0xa4, 0x78, 0x0c, 0x62, 0x5e, 0xd5, 0xec, 0xe1, 0x87, 0x05,
	0x9d, 0xeb, 0x15, 0x98, 0x6c, 0x83, 0x9d, 0x4d, 0x3d, 0x6b, 0x60, 0xf9, 0x9d, 0xc8, 0xce, 0xa6,
	0xe4, 0x1e, 0xda, 0x2c, 0x4e, 0x90, 0x29, 0xcf, 0x1e, 0x38, 0xbe, 0x1b, 0x8e, 0xe9, 0x9f, 0x66,
	0xb4, 0x51, 0xa3, 0x77, 0x86, 0x7a, 0xc3, 0xb5, 0xac, 0xa2, 0xa5, 0x0e, 0xe9, 0x41, 0x2b, 0x9b,
	0xc7, 0x33, 0xf4, 0x1c, 0x63, 0x52, 0x2f, 0xc4, 0x87, 0x2d, 0x95, 0x63, 0xea, 0xb5, 0x06, 0x96,
	0xef, 0x86, 0x3d, 0x5a, 0xe7, 0xa5, 0xab, 0xbc, 0xf4, 0x92, 0x57, 0x91, 0x41, 0xf4, 0xcf, 0xc0,
	0x5d, 0x93, 0x25, 0x5d, 0x70, 0x9e, 0xb1, 0x5a, 0x26, 0x5e, 0x8c, 0x0b, 0x83, 0x32, 0x66, 0x05,
	0x7a, 0x76, 0x6d, 0x60, 0x96, 0x73, 0x7b, 0x6c, 0x0d, 0xf7, 0x61, 0x67, 0x82, 0xba, 0x89, 0x17,
	0xe1, 0x4b, 0x81, 0x4a, 0xff, 0xec, 0x3c, 0x4c, 0xa0, 0xf7, 0x1d, 0xa6, 0x72, 0xc1, 0x15, 0x92,
	0x5b, 0xe8, 0x34, 0x45, 0x0d, 0xdc, 0x0d, 0x0f, 0x36, 0xf9, 0x1d, 0xd1, 0x17, 0x3d, 0x7c, 0xb7,
	0x00, 0x9a, 0x0f, 0x8a, 0x94, 0xe0, 0x4c, 0x50, 0x93, 0x93, 0x7f, 0xc8, 0xfd, 0xd2, 0xa0, 0x7f,
	0xba, 0x31, 0xaf, 0xae, 0x74, 0x75, 0xf4, 0x40, 0x9f, 0x8a, 0xf8, 0x15, 0x33, 0x9a, 0x8a, 0x79,
	0xc0, 0xf3, 0xe2, 0x10, 0xdf, 0x72, 0x21, 0x35, 0xca, 0x20, 0x15, 0x8c, 0x61, 0xaa, 0xc5, 0x62,
	0x5a, 0xd2, 0x2e, 0xca, 0x51, 0xd2, 0x36, 0x4f, 0x72, 0xfc, 0x19, 0x00, 0x00, 0xff, 0xff, 0x30,
	0xcc, 0x1c, 0x74, 0x87, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ContainersClient is the client API for Containers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContainersClient interface {
	Get(ctx context.Context, in *GetContainerRequest, opts ...grpc.CallOption) (*GetContainerResponse, error)
}

type containersClient struct {
	cc grpc.ClientConnInterface
}

func NewContainersClient(cc grpc.ClientConnInterface) ContainersClient {
	return &containersClient{cc}
}

func (c *containersClient) Get(ctx context.Context, in *GetContainerRequest, opts ...grpc.CallOption) (*GetContainerResponse, error) {
	out := new(GetContainerResponse)
	err := c.cc.Invoke(ctx, "/containerd.services.containers.v1.Containers/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContainersServer is the server API for Containers service.
type ContainersServer interface {
	Get(context.Context, *GetContainerRequest) (*GetContainerResponse, error)
}

// UnimplementedContainersServer can be embedded to have forward compatible implementations.
type UnimplementedContainersServer struct {
}

func (*UnimplementedContainersServer) Get(context.Context, *GetContainerRequest) (*GetContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterContainersServer(s *grpc.Server, srv ContainersServer) {
	s.RegisterService(&_Containers_desc, srv)
}

func _Containers_Get_Method(srv interface{}, ctx context.Context, desc func(interface{}) error, itcpt grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContainerRequest)
	if err := desc(in); err != nil {
		return nil, err
	}
	if itcpt == nil {
		return srv.(ContainersServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containerd.services.containers.v1.Containers/Get",
	}
	handler := func(ctx context.Context, request interface{}) (interface{}, error) {
		return srv.(ContainersServer).Get(ctx, request.(*GetContainerRequest))
	}
	return itcpt(ctx, in, info, handler)
}

var _Containers_desc = grpc.ServiceDesc{
	ServiceName: "containerd.services.containers.v1.Containers",
	HandlerType: (*ContainersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Containers_Get_Method,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "containerd.proto",
}
